### ISSUE TITLE
Cohesion & Single Responsibilty

### ISSUE THREAD

**Issue by zer0origin** [7odaifa-ab/TaskTimer#1]
https://github.com/7odaifa-ab/TaskTimer/blob/e07a4754f7a5a77a29de02c941b77642fa2c2f7d/src/main/java/HuimangTech/App.java#L63

This line lowers the cohesion of this program and break Single Responsibilty (as on of the SOLID principles)

**Comment by 7odaifa-ab** [comment]
i really don't get what you mean, is it because it declared Static public? cause I can simply put it back to the Timer Class
